project_name: prometheus-iotdb-exporter
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64  
nfpms:
- maintainer: Fagner Carvalho <fagnerncarvalho@gmail.com>
  description: Prometheus IoTDB exporter.
  homepage: https://github.com/fagnercarvalho/prometheus-iotdb-exporter
  license: MIT
  formats:
  - deb
  - rpm
  - apk
  replacements:
    darwin: macOS 
    386: 32bit    
    amd64: 64bit
    arm: arm32
archives:
  - id: prometheus-iotdb-exporter
    replacements:
      darwin: macOS
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - README.md 
release:
  prerelease: auto
  name_template: "{{.Tag}}"   
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch      